title: VanRed Enterprises
url: "https://vanredenterprises.ca"
baseurl: ""
collections:
  equipment:
    output: true
    permalink: /equipment/:name/
defaults:
  - scope:
      path: ""
      type: equipment
    values:
      layout: equipment
encoding: UTF-8
